version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image:
    container_name: ''
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - applog:/app/log
    restart: always
    networks:
      - app

networks:
  app:

volumes:
  applog: