apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  #advertiseAddress: 0.0.0.0
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
etcd:
  local:
    #image: registry.docker-cn.com/gcrxio/etcd:3.2.24
    #image: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd-amd64:3.2.24
networking:
  podSubnet: 10.244.0.0/16
#imageRepository: registry.docker-cn.com/gcrxio
#imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
