apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  #advertiseAddress: 0.0.0.0
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
apiServerExtraArgs:
  service-node-port-range: 80-65535
networking:
  podSubnet: 10.244.0.0/16
imageRepository: gcr.mirrors.ustc.edu.cn/google-containers
