version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    #command: --max_allowed_packet=10G
    command: --max_allowed_packet=67108864

volumes:
  mysql:

